name: My First Workflow

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      homedrive:
        description: The home drive on the machine
        required: true
      tag:
        description: Apply tag after successful test run
        required: true
        type: boolean
      loglevel:
        description: Log level
        default: warning
        type: choice
        options:
        - info
        - warning
        - error
        - debug

jobs:
  MyFirstJob:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hello World"
      - name: Checkout
        uses: actions/checkout@v6.0.1
      - name: List files in repository
        run:  |
          echo "The repo ${{ github.repository }} contains the following files:"
          tree
          echo "homedrive=${{ inputs.homedrive }}"
          echo "tag=${{ inputs.tag }}"
          echo "loglevel=${{ inputs.tag }}"
